/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Default: typeof import('./core/layouts/default.vue')['default']
    HotelsList: typeof import('@/domains/hotelsList/ui/HotelsList.vue')['default']
    Navbar: typeof import('./core/layouts/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Filters: typeof import('./domains/hotelsList/ui/components/Filters.vue')['default']
  }
}
