/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Default: typeof import('./core/layouts/default.vue')['default']
    DefaultLayout: typeof import('./core/layouts/DefaultLayout.vue')['default']
    Filters: typeof import('./domains/hotelsList/ui/components/Filters.vue')['default']
    GuestsMenu: typeof import('./domains/hotelsList/ui/components/GuestsMenu.vue')['default']
    HotelCard: typeof import('./domains/hotelsList/ui/components/HotelCard.vue')['default']
    HotelsList: typeof import('./domains/hotelsList/ui/HotelsList.vue')['default']
    HotelsListContent: typeof import('./domains/hotelsList/ui/components/HotelsListContent.vue')['default']
    Navbar: typeof import('./core/layouts/components/Navbar.vue')['default']
    RoomsModal: typeof import('./domains/hotelsList/ui/components/RoomsModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
